### PR TITLE
bump the serverless-localstack plugin version

### PR DESCRIPTION
**Pull request by HarshCasper**

### CODE REVIEW

**Review by joe4dev — APPROVED** [review]
LGTM 👍 

Fixes a bunch of issues (see [changelog](https://github.com/localstack/serverless-localstack#change-log))

**Comment by joe4dev** [comment]
nit: it would be ideal to commit the updated `yarn.lock` file as well to track the pinned dependencies

**Comment by joe4dev** [comment]
as well as the apps version

**Review by MarcelStranak — APPROVED** [review]
LGTM

**Pull request merged**
