### PR TITLE
Align with quickstart guide instructions

### PR DESCRIPTION
**Pull request by simonrw**
The quickstart guide uses `npm` but we use `yarn` here.

### CODE REVIEW

**Comment by simonrw** [comment]
@HarshCasper in [your previous PR](https://github.com/localstack/localstack-demo/pull/57) you switched from `npm` to `yarn` - do you remember why?

**Comment by simonrw** [comment]
> Not exactly — Do you have a strong preference between `npm` or `yarn`? We can switch to either.

It is only that if we use `npm` we are aligned with our [getting started guide](https://docs.localstack.cloud/getting-started/quickstart/#run-the-sample-aws-application).

See how the instructions below the heading I linked mention `npm` but not `yarn`.

**Comment by alexrashed** [comment]
FYI: This PR would resolve https://github.com/localstack/docs/issues/795.
I would be in favor of `npm`. It comes pre-shipped with every node environment, no need to install anything else.

**Review by alexrashed — APPROVED** [review]
Awesome, thanks for adjusting the sample! I would be in favor of npm, as it comes pre-shipped with every node environment, no need to install anything else. 🚀 
FYI: This PR would resolve https://github.com/localstack/docs/issues/795.

**Pull request merged**
